services:
  - docker

language: node_js
node_js:
  - "8"
dist: xenial

stages:
  - build
  - test
  - name: deploy
    if: branch = master

install:
  - npm install

jobs:
  include:
    - stage: build
      name: "Build the Compiler"
    - stage: test
      name: "Unit Tests"
      before_script: npm run pretest
      script: node_modules/mocha/bin/mocha --reporter list
    - name: "Integration Tests"
      before_install: sudo apt-get install valgrind
      before_script: npm run build
      script: test/run_tests.sh
      env: SLOW_TESTS=y
    - stage: deploy
      name: "Deploy to npmjs"
      env: TARGET=npmjs
    - name: Fedora 29
      env: OS=fedora DIST=29
    - name: Fedora 30
      env: OS=fedora DIST=30
    - name: Debian Buster
      env: OS=debian DIST=buster
    - name: Ubuntu Cosmic Cuttlefish
      env: OS=ubuntu DIST=cosmic
    - name: Ubuntu Disco Dingo
      env: OS=ubuntu DIST=disco

script:
  - npm run build
  - make package

deploy:
  - provider: npm
    email: $NPM_MAIL_ADDRESS
    api_key: $NPM_PUBLISH_TOKEN
    skip_cleanup: true
    on:
      branch: master
      condition: "x${TARGET} = xnpmjs"
  - provider: packagecloud
    repository: fyrlang
    username: vs-ude
    token: $PACKAGECLOUD_TOKEN
    dist: "${OS}/${DIST}"
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: "master"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
