language: node_js
node_js:
  - "8"
dist: xenial
stages:
  - build
  - test
  - deploy
before_install:
  - sudo apt-get install gcc valgrind
install:
  - export FYRBASE=$PWD
  - npm install
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      before_script: npm run pretest
      script: node_modules/mocha/bin/mocha --reporter list
    - before_script: npm run pretest
      script: test/run_tests.sh
    - stage: deploy
      before_script: npm run build
      script: echo "Deploying to npm"
      deploy:
        provider: npm
        email: $NPM_MAIL_ADDRESS
        api_key: $NPM_PUBLISH_TOKEN
        on:
          branch: master
