language: node_js
node_js:
  - "8"
dist: xenial
stages:
  - build
  - test
  - deploy
before_install:
  - sudo apt-get install gcc valgrind
install:
  - export FYRBASE=$PWD
  - npm install
jobs:
  include:
    - stage: build
      script: npm build
    - script: npm pretest
    - stage: test
      script: node_modules/mocha/bin/mocha --reporter list
    - script: test/run_tests.sh
    - stage: deploy
      script: echo "Deploying to npm"
      deploy:
        provider: npm
        email: $NPM_MAIL_ADDRESS
        api_key: $NPM_PUBLISH_TOKEN
        on:
          branch: master
