Summary: An experimental compiler for IoT applications
Name: fyrlang
Version: autogenerated
Release: autogenerated
License: BSD-3-Clause
Source: autogenerated
URL: http://fyr.vs.uni-due.de/
Packager: Oskar Carl <oskar.carl@uni-due.de>

%description

%prep

%install
ln -s %{_bindir}/fyrc %{_datarootdir}/bin/fyrc

%post
# Fix security context for SELinux
# http://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
chcon -Rt svirt_sandbox_file_t %{_datarootdir}/fyrlang/ || :

%files
%{_datarootdir}/fyrlang/*
%doc README.md
%{!?_licensedir:%global license %doc}
%license LICENSE.md
